### ISSUE TITLE
JavaScript error after finishing last puzzle

### ISSUE THREAD

**Issue by jaredkrinke** [jaredkrinke/sic1#317]
```
Uncaught TypeError: Cannot read properties of undefined (reading 'title')
    at new Xt (index.js:1:250485)
    at _ (index.js:1:5577)
    at w (index.js:1:3334)
    at index.js:1:8169
    at _ (index.js:1:8522)
    at w (index.js:1:3334)
    at index.js:1:8169
    at _ (index.js:1:8522)
    at w (index.js:1:3334)
    at index.js:1:8169
```

**Comment by jaredkrinke** [comment]
This happened while I was testing the Steam version with a clean data file. I did rebuild the JS part of the project, but that shouldn't matter.

Does this happen every time?

**Comment by jaredkrinke** [comment]
This seems like an issue that's existed for a long time... I wonder why I didn't see any automatic error reports for it...
