### ISSUE TITLE
Investigate error in console

### ISSUE THREAD

**Issue by jaredkrinke** [jaredkrinke/sic1#55]
index.6ffef15d.js:1 
        
       Uncaught TypeError: Cannot read properties of null (reading 'value')
    at ce.getCode (index.6ffef15d.js:1:55203)
    at fe.saveProgress (index.6ffef15d.js:1:68864)
    at Object.onSaveRequested [as blurfalse] (index.6ffef15d.js:1:81508)
    at HTMLTextAreaElement.x (index.6ffef15d.js:1:3620)
    at c (index.6ffef15d.js:1:183)
    at T (index.6ffef15d.js:1:7655)
    at y (index.6ffef15d.js:1:2213)
    at index.6ffef15d.js:1:6645
    at w (index.6ffef15d.js:1:6998)
    at y (index.6ffef15d.js:1:1810)
getCode @ index.6ffef15d.js:1
saveProgress @ index.6ffef15d.js:1
onSaveRequested @ index.6ffef15d.js:1
x @ index.6ffef15d.js:1
c @ index.6ffef15d.js:1
T @ index.6ffef15d.js:1
y @ index.6ffef15d.js:1
(anonymous) @ index.6ffef15d.js:1
w @ index.6ffef15d.js:1
y @ index.6ffef15d.js:1
(anonymous) @ index.6ffef15d.js:1
w @ index.6ffef15d.js:1
y @ index.6ffef15d.js:1
w @ index.6ffef15d.js:1
y @ index.6ffef15d.js:1
w @ index.6ffef15d.js:1
(anonymous) @ index.6ffef15d.js:1
f @ index.6ffef15d.js:1
setTimeout (async)
g @ index.6ffef15d.js:1
h.setState @ index.6ffef15d.js:1
loadPuzzle @ index.6ffef15d.js:1
onClick @ index.6ffef15d.js:1
onClick @ index.6ffef15d.js:1
x @ index.6ffef15d.js:1

**Comment by jaredkrinke** [comment]
Might be related to saving progress. That would be important to fix!

**Comment by jaredkrinke** [comment]
Saving seems to work, at least, so maybe not a big deal.

The textarea reference is null, but I'm not sure why yet.

**Comment by jaredkrinke** [comment]
Hmmm... I can't reproduce the error when debugging, but it happens otherwise when switching puzzles.

**Comment by jaredkrinke** [comment]
Probably related to Sic1Ide's puzzle being a property instead of a state, e.g. if it changes then the component needs to be recreated.
